### PR TITLE
Switch to pyautogui

### LINKED ISSUE #34: Anything but keybinds broken when running as root on ubuntu
Currently investigating this issue, will update this issue when I have more info
`pyautogui` could possibly fix this issue ( https://github.com/nimaid/LPHK/issues/11#issuecomment-564291954 )

### PR DESCRIPTION
**Pull request by duncte123**
Fixes #34

### CODE REVIEW

**Comment by duncte123** [comment]
Current findings on ubuntu 18.04:
pynput throws with releasing media keys in gnome
pyautogui silently fails

**Comment by duncte123** [comment]
This needs a lot of testing but it should work

**Comment by duncte123** [comment]
This PR is confirmed to be working with the MK3 as well

**Comment by duncte123** [comment]
Currently doesn't work with the following games
- factorio: both windowed and full screen

**Comment by NullMember** [comment]
If you're switching to pyautogui, keyboard events on win32 directinput driven applications will not respond keyboard events. You can write your own keyboard library using win32 api calls or (I recommend) just continue to use keyboard library for windows platform only (or add a new keywords like "@GAME" or something to use keyboard library calls on windows for not working games and applications). If you're going to write new keyboard library using win32 calls I can help. 
Just a little background:
(unfortunately for me) I already wrote a few lines of code to my local LPHK build. I play age of empires 3 with my friends and LPHK not worked for it. I thought it was directinput issue. Instead of trying something else I wrote new keyboard library from scratch and it's not worked too *sigh*. Later I found it's not working because game running on admin rights  *shame*. I've used pywin32 (adds new dependency) to use win32 api calls but it's possible to use just built-in ctypes (no dependency).

**Comment by duncte123** [comment]
> If you're switching to pyautogui, keyboard events on win32 directinput driven applications will not respond keyboard events. You can write your own keyboard library using win32 api calls or (I recommend) just continue to use keyboard library for windows platform only (or add a new keywords like "@GAMe" or something to use keyboard library calls on windows for not working games and applications). If you're going to write new keyboard library using win32 calls I can help.
> Just a little background:
> (unfortunately for me) I already wrote a few lines of code to my local LPHK build. I play age of empires 3 with my friends and LPHK not worked for it. I thought it was directinput issue. Instead of trying something else I wrote new keyboard library from scratch and it's not worked too _sigh_. Later I found it's not working because game running on admin rights _shame_. I've used pywin32 (adds new dependency) to use win32 api calls but it's possible to use just built-in ctypes (no dependency).

We recently found this out ourselves and are trying to find a good solution.
I saw your PR (#38) earlier today and I'm going to test and merge it soon.
You're welcome to implement a fix for win32 as a PR to this branch we just have to make sure to also support macOS and GNU/Linux.

**Pull request merged**
